name: Cleanup Docker packages

on:
  workflow_call:
    inputs:
      min_versions_to_keep:
        description: 'Minimum versions to keep for main package'
        required: false
        default: '10'
        type: string
      min_base_versions_to_keep:
        description: 'Minimum versions to keep for base package'
        required: false
        default: '10'
        type: string
      force_cleanup:
        description: 'Force aggressive cleanup (removes more versions)'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      min_versions_to_keep:
        description: 'Minimum versions to keep for main package'
        required: false
        default: '10'
        type: string
      min_base_versions_to_keep:
        description: 'Minimum versions to keep for base package'
        required: false
        default: '10'
        type: string
      force_cleanup:
        description: 'Force aggressive cleanup (removes more versions)'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup temporary artifacts and old packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set cleanup parameters
        id: params
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "min_versions=${{ inputs.min_versions_to_keep }}" >> $GITHUB_OUTPUT
            echo "min_base_versions=${{ inputs.min_base_versions_to_keep }}" >> $GITHUB_OUTPUT
            if [ "${{ inputs.force_cleanup }}" = "true" ]; then
              echo "min_versions=3" >> $GITHUB_OUTPUT
              echo "min_base_versions=3" >> $GITHUB_OUTPUT
            fi
          else
            echo "min_versions=10" >> $GITHUB_OUTPUT
            echo "min_base_versions=10" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all untagged package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'latex-compiler'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old tagged package versions (keep only 10 most recent)
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'latex-compiler'
          package-type: 'container'
          min-versions-to-keep: ${{ steps.params.outputs.min_versions }}
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete all untagged package versions (base image)
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'latex-compiler/base'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Delete old tagged package versions (base image, keep only 10 most recent)
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'latex-compiler/base'
          package-type: 'container'
          min-versions-to-keep: ${{ steps.params.outputs.min_base_versions }}
          delete-only-untagged-versions: false
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Clean up Docker system
        run: |
          docker system prune -af --volumes
        continue-on-error: true

      - name: Report cleanup completion
        run: |
          echo "✅ Cleanup completed successfully"
          echo "- Deleted ALL untagged versions"
          echo "- Kept ${{ steps.params.outputs.min_versions }} most recent tagged versions (main package)"
          echo "- Kept ${{ steps.params.outputs.min_base_versions }} most recent tagged versions (base package)"
          echo "- Cleaned up Docker system resources"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "- Triggered manually with custom parameters"
          else
            echo "- Triggered automatically from main workflow"
          fi
