name: Build and Push Docker Images

on:
  push:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'base.Dockerfile'
      - '.github/workflows/**'
      - 'texlive-packages*.txt'
      - 'apt-packages*.txt'
      - 'texlive-profile*.txt'
      - 'compile.sh'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'Dockerfile'
      - 'base.Dockerfile'
      - '.github/workflows/**'
      - 'texlive-packages*.txt'
      - 'apt-packages*.txt'
      - 'texlive-profile*.txt'
      - 'compile.sh'
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild even without changes'
        required: false
        default: false
        type: boolean
  schedule:
    # Monthly rebuild to get latest TeX Live updates (first Sunday of each month at 2 AM UTC)
    - cron: '0 2 1-7 * 0'

permissions:
  contents: read
  packages: write

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  build:
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      matrix: ${{ needs.prepare.outputs.matrix }}
      build_date: ${{ needs.prepare.outputs.build_date }}
      should_release: ${{ needs.prepare.outputs.should_release }}
      base_image_tag: ${{ needs.prepare.outputs.base_image_tag }}
    secrets: inherit
    permissions:
      contents: read
      packages: write

  test:
    needs: [prepare, build]
    uses: ./.github/workflows/test.yml
    with:
      matrix: ${{ needs.prepare.outputs.matrix }}
      base_image_tag: ${{ needs.prepare.outputs.base_image_tag }}
    secrets: inherit

  publish:
    needs: [prepare, build, test]
    uses: ./.github/workflows/publish.yml
    with:
      matrix: ${{ needs.prepare.outputs.matrix }}
      build_date: ${{ needs.prepare.outputs.build_date }}
      should_release: ${{ needs.prepare.outputs.should_release }}
      base_image_tag: ${{ needs.prepare.outputs.base_image_tag }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
